# Generated by Django 5.2.7 on 2025-11-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll', 'classroom')},
        ),
    ]
